### ISSUE TITLE
Fancy terminal colors does not work for Windows command prompt

### ISSUE THREAD

**Issue by tlitetrasci** [tetrascience/ts-sdk-python#34]
The fancy terminal colors we add to the error message [here](https://github.com/tetrascience/ts-sdk-python/blob/666e34d15535c6af5e22171dbc9b71c3e6f711fe/ts_sdk/cli/__api.py#L14) does not work for Windows users using the basic command prompt.

The Windows user instead sees:

```
?[91morg is not set!?[0m
?[91mapi_url is not set!?[0m
?[91mauth_token is not set!?[0m
```

**Comment by yandryianets** [comment]
v1.2.8 tested on VM
